/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "MyVpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "ProcessTranscriptionQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "ProcessTranscriptionWorker": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
